services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rag_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333

volumes:
  postgres_data: