import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider
          refetchInterval={5 * 60} // Refetch every 5 minutes (default is every 30 seconds!)
          refetchOnWindowFocus={false} // Don't refetch when window gains focus
          refetchWhenOffline={false} // Don't refetch when coming back online
        >
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
